# Generated by Django 2.1.5 on 2019-05-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='county',
        ),
    ]
