# Generated by Django 2.1.5 on 2019-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190828_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
