# Generated by Django 2.1.5 on 2019-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20190823_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='is_4rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='is_4sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedroom',
            field=models.ManyToManyField(help_text='Select how many bedrooms  Your Posting', to='houses.Bedroom'),
        ),
        migrations.AddField(
            model_name='house',
            name='type_of_house',
            field=models.ManyToManyField(help_text='Select The kind of House Your Posting your', to='houses.Type_of_house'),
        ),
    ]
