# Generated by Django 2.1.5 on 2019-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20190831_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_4rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_4sale',
            field=models.BooleanField(default=False),
        ),
    ]
