# Generated by Django 2.1.5 on 2019-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20190831_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='bathrooms',
        ),
        migrations.AlterField(
            model_name='house',
            name='bedroom',
            field=models.ManyToManyField(help_text='Select how many bedrooms', to='houses.Bedroom'),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.ManyToManyField(help_text='Select how many bathrooms', to='houses.Bathroom'),
        ),
    ]
