# Generated by Django 2.1.5 on 2019-09-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20190831_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_4rent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='is_4sale',
        ),
    ]
