# Generated by Django 2.1.5 on 2019-08-22 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190821_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='links/%Y/%m/%d/')),
                ('link_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
