# Generated by Django 2.1.5 on 2019-08-30 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_name', models.CharField(max_length=200)),
                ('link_url', models.CharField(max_length=200, null=True)),
                ('link_pic', models.ImageField(blank=True, null=True, upload_to='links/%Y/%m/%d/')),
                ('link_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
