# Generated by Django 2.1.5 on 2019-08-26 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('agreed_buying_price', models.IntegerField(null=True)),
                ('deposit_paid', models.IntegerField(blank=True, null=True)),
                ('payment_paid', models.IntegerField(null=True)),
                ('total_amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('is_published', models.IntegerField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
