# Generated by Django 2.1.5 on 2019-08-26 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190826_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_made', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='payment_paid',
            new_name='total_payments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_amount_paid',
        ),
        migrations.AddField(
            model_name='property_id',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='property_id',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property_id',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='property_id',
        ),
        migrations.AddField(
            model_name='account',
            name='property_id',
            field=models.ManyToManyField(help_text='Select your properties', to='accounts.Property_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='payments',
            field=models.ManyToManyField(help_text='Select Payments', to='accounts.Payment'),
        ),
    ]
