# Generated by Django 2.1.5 on 2019-08-26 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190826_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Property_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_expected', models.IntegerField(help_text='buyers agreed buying price', null=True)),
                ('deposit_paid', models.IntegerField(blank=True, null=True)),
                ('payment_made', models.CharField(max_length=200, null=True)),
                ('total_payments', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ManyToManyField(help_text='Select The Buyer', to='accounts.Buyer')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='Buyer',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='agreed_buying_price',
            new_name='total_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='total_payments_expected',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_payments',
        ),
        migrations.AddField(
            model_name='account',
            name='all_Propertys_owned',
            field=models.ManyToManyField(help_text='Select Property', to='accounts.Property_id'),
        ),
        migrations.AddField(
            model_name='property_id',
            name='property_price_tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='property_payment',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Property_id'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='property_id',
            field=models.ManyToManyField(help_text='Select your properties', to='accounts.Property_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_payments_made',
            field=models.ManyToManyField(help_text='Select Payments', to='accounts.Property_payment'),
        ),
    ]
