# Generated by Django 2.1.5 on 2019-08-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190827_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='property_id',
            new_name='property_bought',
        ),
        migrations.RemoveField(
            model_name='property_payment',
            name='property_id',
        ),
        migrations.AddField(
            model_name='property_payment',
            name='property_bought',
            field=models.ManyToManyField(help_text='Select your properties', to='accounts.Property_id'),
        ),
    ]
