# Generated by Django 2.1.5 on 2019-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190827_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_made',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
