# Generated by Django 2.1.5 on 2019-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190827_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
