# Generated by Django 2.1.5 on 2019-08-27 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190827_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
