# Generated by Django 2.1.5 on 2019-08-27 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20190827_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_bought', models.ManyToManyField(help_text='all properties bought by buyer', to='accounts.Property_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_made',
        ),
        migrations.AddField(
            model_name='account',
            name='payment_made',
            field=models.ManyToManyField(help_text='Select your payments made so far', to='accounts.Payment'),
        ),
    ]
